server:
  port: 9001
#mybatis配置
mybatis:
  type-aliases-package: com.zhangshun.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#spring配置
spring:
  application:
    name: zhang-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db03?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root


#EUREKA 配置
eureka:
  client:
    service-url:
      defaultZone: http://zhang1:8001/eureka/,http://zhang2:8002/eureka/,http://zhang3:8003/eureka/
  instance:
    instance-id: zhang-provider3

#info 配置信息、
info:
  app.name: zhang-springcloud
  company.name: teyongxin
