server:
  port: 8001

#eureka 配置
eureka:
  instance:
    hostname: zhang1 #eureka 服务端的名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #fetch-registry 如果为false，这表示自己为注册中心
    service-url:  #监控页面
      defaultZone: http://zhang2:8002/eureka/,http://zhang3:8003/eureka/

